name: Coverage
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Lists tests
        run: cargo test -- --list
      
      - name: Run tests
        run: cargo test --verbose

      - name: Generate code coverage
        run: |
          cargo install cargo-tarpaulin
          time cargo tarpaulin --ignore-tests -o Html -o Lcov --timeout 240 --engine llvm

      - name: Upload to coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          file: lcov.info
          token: ${{secrets.COVERALLS_REPO_TOKEN}}
          fail_ci_if_error: true
      
      - name: Upload coverage report to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: tarpaulin-report.html